version: '3.7'
services:
  pw-reset-web:
    build:
      context: .
      args:
        PROJECT_NAME: pw-reset-web
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5050:80"
    restart: always
    networks: 
      - pw-reset
  
  pw-reset-api:
    build:
      context: .
      args:
        PROJECT_NAME: pw-reset-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5051:80"
    restart: always
    networks: 
      - pw-reset

  database:
    image: store/oracle/database-enterprise:12.2.0.1
    volumes:
      - /home/oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
    environment:
      ORACLE_PWD: F1abcd@test
    ports:
      - 1521:1521
      - 8000:8080
      - 5500:5500

networks:
  pw-reset:
