version: '3.7'
services:
  pw-reset-web:
    build:
      context: .
      args:
        PROJECT_NAME: pw-reset-web
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5050:80"
    restart: always
    networks: 
      - pw-reset
  
  pw-reset-api:
    build:
      context: .
      args:
        PROJECT_NAME: pw-reset-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5051:80"
    restart: always
    networks: 
      - pw-reset

  database:
    build:
        context: https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance/dockerfiles/12.2.0.1
        dockerfile: Dockerfile.ee
    #build:
    #  context: .
    #  dockerfile: ./scripts/oracle.dockerfile 
    volumes:
      #- ./scripts:/docker-entrypoint-initdb.d/startup
      #- ./scripts:/opt/oracle/scripts/
      - ./scripts:/opt/oracle/scripts/setup
      #- .\scripts\01_createUser.sql:/docker-entrypoint-initdb.d/01_createUser.sql
      - /opt/oracle/oradata # persistent oracle database data.
    #command: ["/u01/app/oracle/product/12.2.0/dbhome_1/bin/sqlplus","system/test123@orclcdb","@/opt/oracle/scripts/startup/01CreateUser.sql"]
    #command: ["/opt/oracle/scripts/startup.sh"]
    environment:
      ORACLE_PWD: F1abcd@test
    networks: 
      - pw-reset
    ports:
      - 1521:1521
      - 8000:8080
      - 5500:5500

networks:
  pw-reset:
    driver: "bridge"
