--alter user sys identified by test1234;
CREATE USER "C##ORACLE" IDENTIFIED BY "123456"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "C##ORACLE" QUOTA UNLIMITED ON "SYSTEM";
ALTER USER "C##ORACLE" QUOTA UNLIMITED ON "SYSAUX";
ALTER USER "C##ORACLE" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "C##ORACLE" WITH ADMIN OPTION;
GRANT CREATE SESSION TO "C##ORACLE" WITH ADMIN OPTION;
GRANT "DBA" TO "C##ORACLE" WITH ADMIN OPTION;

-- SYSTEM PRIVILEGES
GRANT ALTER USER TO "C##ORACLE" WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO "C##ORACLE" WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO "C##ORACLE" WITH ADMIN OPTION;

select * from all_users;